export const ZOMATO_STORES = [
  { id: "Z001", name: "ADARSH PALM RETREAT - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22327622" },
  { id: "Z002", name: "Adugodi - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21012956" },
  { id: "Z003", name: "Adyar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366215" },
  { id: "Z004", name: "Airoli - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21446718" },
  { id: "Z005", name: "Aliganj - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21503269" },
  { id: "Z006", name: "Alpha 2 - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21689875" },
  { id: "Z007", name: "Anantapur - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20845580" },
  { id: "Z008", name: "Andheri - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365940" },
  { id: "Z009", name: "Andheri West - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20405575" },
  { id: "Z010", name: "Arumbakkam - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366221" },
  { id: "Z011", name: "As Rao Nagar - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20365636" },
  { id: "Z012", name: "Ashok Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21469944" },
  { id: "Z013", name: "Athwa - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20600037" },
  { id: "Z014", name: "Attapur - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20365639" },
  { id: "Z015", name: "Bachupally - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22332192" },
  { id: "Z016", name: "Ballygunge - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "" },
  { id: "Z017", name: "Banashankari - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366199" },
  { id: "Z018", name: "Banaswadi - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366251" },
  { id: "Z019", name: "Bandra - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366246" },
  { id: "Z020", name: "Baner - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20400793" },
  { id: "Z021", name: "Banjara Hills - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20365625" },
  { id: "Z022", name: "Basveshwaranagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365566" },
  { id: "Z023", name: "Behala - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21288904" },
  { id: "Z024", name: "Belghoria - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21402781" },
  { id: "Z025", name: "Bellandur - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366260" },
  { id: "Z026", name: "Beltola - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21343659" },
  { id: "Z027", name: "Benz Circle - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366015" },
  { id: "Z028", name: "Bhavanipuram - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366033" },
  { id: "Z029", name: "Borivali - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365958" },
  { id: "Z030", name: "Brodipet - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365909" },
  { id: "Z031", name: "Brookfield - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20917537" },
  { id: "Z032", name: "Btm - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366272" },
  { id: "Z033", name: "Ca Road - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20762159" },
  { id: "Z034", name: "Chandkhed - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20495911" },
  { id: "Z035", name: "Chembur - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365977" },
  { id: "Z036", name: "Choodasandra - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20739969" },
  { id: "Z037", name: "Chrompet - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20845581" },
  { id: "Z038", name: "Cidco - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20777456" },
  { id: "Z039", name: "Colaba - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20471334" },
  { id: "Z040", name: "Cunningham Road - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22037348" },
  { id: "Z041", name: "Cuttack - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22246205" },
  { id: "Z042", name: "Dharwad - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20845583" },
  { id: "Z043", name: "Dilshad Garden - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21688538" },
  { id: "Z044", name: "Dilsukhnagar - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20365995" },
  { id: "Z045", name: "Dombivali - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21550497" },
  { id: "Z046", name: "Dommasandra - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20725450" },
  { id: "Z047", name: "Dwarka Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366060" },
  { id: "Z048", name: "Electronic City - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365929" },
  { id: "Z049", name: "Erode - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20486967" },
  { id: "Z050", name: "Galleria - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365912" },
  { id: "Z051", name: "Gandhi Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20495896" },
  { id: "Z052", name: "Garia - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21572306" },
  { id: "Z053", name: "Gaur City - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20646571" },
  { id: "Z054", name: "Gomtinagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21092007" },
  { id: "Z055", name: "Gotri - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20845590" },
  { id: "Z056", name: "Govindpura - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21477961" },
  { id: "Z057", name: "Hauz Khaz - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20435045" },
  { id: "Z058", name: "Hbr Layout - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365954" },
  { id: "Z059", name: "Hennur - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365979" },
  { id: "Z060", name: "Himayat Nagar - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20365641" },
  { id: "Z061", name: "Hopes - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366068" },
  { id: "Z062", name: "IMT Ghaziabad - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21689973" },
  { id: "Z063", name: "Indiranagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365989" },
  { id: "Z064", name: "Jalukbadi - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22327557" },
  { id: "Z065", name: "Jalvayu Towers - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365916" },
  { id: "Z066", name: "Jeevan Bhimnagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365686" },
  { id: "Z067", name: "JP Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365682" },
  { id: "Z068", name: "Kadugudi - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20376394" },
  { id: "Z069", name: "Kailash Vihar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21534569" },
  { id: "Z070", name: "Kakinada - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20424634" },
  { id: "Z071", name: "Kakkanad - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366186" },
  { id: "Z072", name: "Kalamassery - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22048673" },
  { id: "Z073", name: "Kaloor - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21730702" },
  { id: "Z074", name: "Kalyan - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21550583" },
  { id: "Z075", name: "Kankarbagh - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21902193" },
  { id: "Z076", name: "Karolbagh - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21345568" },
  { id: "Z077", name: "Kengeri - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365693" },
  { id: "Z078", name: "Kharaghar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365951" },
  { id: "Z079", name: "Kharar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20471451" },
  { id: "Z080", name: "Kk Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366048" },
  { id: "Z081", name: "Kokapet - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22103713" },
  { id: "Z082", name: "Kompally - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20365646" },
  { id: "Z083", name: "Kondhwa - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365563" },
  { id: "Z084", name: "Koramangla - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365695" },
  { id: "Z085", name: "Kothrud - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365565" },
  { id: "Z086", name: "Kudlu - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365564" },
  { id: "Z087", name: "Kukatpally - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20365981" },
  { id: "Z088", name: "Kurnool - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20844898" },
  { id: "Z089", name: "Kuvempunagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366286" },
  { id: "Z090", name: "Lalbagh - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366001" },
  { id: "Z091", name: "Lalpur - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21469977" },
  { id: "Z092", name: "Laxmi Sagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22045946" },
  { id: "Z093", name: "Lingampally - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20366027" },
  { id: "Z094", name: "Lohegaon - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20471181" },
  { id: "Z095", name: "Lower Parel - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366232" },
  { id: "Z096", name: "Ludhiana - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20876045" },
  { id: "Z097", name: "Madhapur - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20366041" },
  { id: "Z098", name: "Madhurawada - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365540" },
  { id: "Z099", name: "Madurai - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20631481" },
  { id: "Z100", name: "Mahadevapura - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365568" },
  { id: "Z101", name: "Malad West - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365691" },
  { id: "Z102", name: "Malviya Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366012" },
  { id: "Z103", name: "Malviya Nagar JP - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365550" },
  { id: "Z104", name: "Manikonda - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20365534" },
  { id: "Z105", name: "Manish Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21447150" },
  { id: "Z106", name: "Mathikere - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20758800" },
  { id: "Z107", name: "Matunga - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20737779" },
  { id: "Z108", name: "Mayur Vihar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365904" },
  { id: "Z109", name: "Mira Road - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365694" },
  { id: "Z110", name: "Miyapur - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20365923" },
  { id: "Z111", name: "Model Town - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22155177" },
  { id: "Z112", name: "Mogappair - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366057" },
  { id: "Z113", name: "Mulund - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20404678" },
  { id: "Z114", name: "Mundhwa - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365567" },
  { id: "Z115", name: "Nad - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365543" },
  { id: "Z116", name: "Nanakramguda - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20365944" },
  { id: "Z117", name: "Nashik - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20779757" },
  { id: "Z118", name: "Nellore - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365562" },
  { id: "Z119", name: "Nerul - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366319" },
  { id: "Z120", name: "Newtown - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21079488" },
  { id: "Z121", name: "Noida 10 - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20400677" },
  { id: "Z122", name: "Noida 49 - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20400727" },
  { id: "Z123", name: "Noida 63 - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20400616" },
  { id: "Z124", name: "Okhila - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366020" },
  { id: "Z125", name: "Palam Vihar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365626" },
  { id: "Z126", name: "Panchkula - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20471366" },
  { id: "Z127", name: "Panvel - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21288858" },
  { id: "Z128", name: "Perumbakkam - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20451061" },
  { id: "Z129", name: "Pimpiri - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366254" },
  { id: "Z130", name: "Powai - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365700" },
  { id: "Z131", name: "Puthiyara Road - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22306877" },
  { id: "Z132", name: "Raipur - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22103569" },
  { id: "Z133", name: "Rajahmundry - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20424613" },
  { id: "Z134", name: "Rajaji Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365528" },
  { id: "Z135", name: "Rajakilpakkam - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365936" },
  { id: "Z136", name: "Rajarhat - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21401768" },
  { id: "Z137", name: "Rajbaha Road - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21552445" },
  { id: "Z138", name: "Ramdaspeth - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20762067" },
  { id: "Z139", name: "Ramtekdi - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366281" },
  { id: "Z140", name: "Rani Bagh - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366025" },
  { id: "Z141", name: "Ranjit Avenue - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21572353" },
  { id: "Z142", name: "Ravet - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21550731" },
  { id: "Z143", name: "Rohini - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21345723" },
  { id: "Z144", name: "Saguna More - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22318291" },
  { id: "Z145", name: "Sahakar Marg - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20659594" },
  { id: "Z146", name: "Sahjivan Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21359729" },
  { id: "Z147", name: "Salem - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20405745" },
  { id: "Z148", name: "Sanjaynagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365531" },
  { id: "Z149", name: "Sant Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22012726" },
  { id: "Z150", name: "Sarjapur - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20417734" },
  { id: "Z151", name: "Sbc - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366074" },
  { id: "Z152", name: "Sector 24 - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20600582" },
  { id: "Z153", name: "Sector 31 - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20451374" },
  { id: "Z154", name: "Sector 63 - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20471325" },
  { id: "Z155", name: "Shahpura - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21446904" },
  { id: "Z156", name: "Shibpur - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21402683" },
  { id: "Z157", name: "Shivajinagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366294" },
  { id: "Z158", name: "Siliguri - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21422221" },
  { id: "Z159", name: "Siruseri - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20682943" },
  { id: "Z160", name: "SN Junction - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22318263" },
  { id: "Z161", name: "Sohn Road - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365631" },
  { id: "Z162", name: "South Dum Dum - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "" },
  { id: "Z163", name: "Steel Plant - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365546" },
  { id: "Z164", name: "Subhash Road - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21291222" },
  { id: "Z165", name: "Svp - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365993" },
  { id: "Z166", name: "T Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365957" },
  { id: "Z167", name: "Tarnaka - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20365963" },
  { id: "Z168", name: "Thane Anand Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21534680" },
  { id: "Z169", name: "Thane West - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366275" },
  { id: "Z170", name: "Thoraipakkam - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365970" },
  { id: "Z171", name: "Thrissur - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20659857" },
  { id: "Z172", name: "Tirupati - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365990" },
  { id: "Z173", name: "Tiruppur - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20471351" },
  { id: "Z174", name: "Trichy - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20522721" },
  { id: "Z175", name: "Uppal - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20365541" },
  { id: "Z176", name: "Vaishali Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366154" },
  { id: "Z177", name: "Vanasthali Puram - Cheesecakes By CakeZone - Online-Periscope", brand: "CakeZone", zomato_id: "20440974" },
  { id: "Z178", name: "Varthur Road - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366203" },
  { id: "Z179", name: "Vasanth Kunj - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20401063" },
  { id: "Z180", name: "Vashi - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366300" },
  { id: "Z181", name: "Vastrapur - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20481660" },
  { id: "Z182", name: "Vasundhara - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20455561" },
  { id: "Z183", name: "Velachery - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365982" },
  { id: "Z184", name: "Vijay Nagar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21359725" },
  { id: "Z185", name: "Virar - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21503188" },
  { id: "Z186", name: "Wagholi - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20481659" },
  { id: "Z187", name: "Wakad - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20366306" },
  { id: "Z188", name: "Warangal - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20435132" },
  { id: "Z189", name: "Whitefield - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365532" },
  { id: "Z190", name: "Yelahanka New Town - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20365533" },
  { id: "Z191", name: "Zirakpur - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21234601" },
  { id: "Z192", name: "Zoo Tiniali - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "21343742" },
  { id: "Z193", name: "Kodigehalli - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "20418014" },
  { id: "Z194", name: "BASAVANAGUDI - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22327986" },
  { id: "Z195", name: "Kunnumpuram Road - Cheesecakes By CakeZone - Online", brand: "CakeZone", zomato_id: "22120577" },
];