import CAKEZONE_STORES from './cakezone_stores.json';
import EATFIT_STORES from './eatfit_stores.json';

export const STORES = [
  ...CAKEZONE_STORES,
  ...EATFIT_STORES,
  { id:"ST01", name:"Commissary", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-63039", status:"offline" },
  { id:"ST02", name:"Keelkattalai", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-55601", status:"offline" },
  { id:"ST03", name:"Madipakkam", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-55602", status:"offline" },
  { id:"ST04", name:"Mudichur", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-55603", status:"offline" },
  { id:"ST05", name:"Mugalivakkam", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-55604", status:"offline" },
  { id:"ST06", name:"Nanganallur", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-55605", status:"offline" },
  { id:"ST07", name:"Pammal", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-55606", status:"offline" },
  { id:"ST08", name:"Perumbakkam", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-55607", status:"offline" },
  { id:"ST09", name:"Rajakilpakkam", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-55608", status:"offline" },
  { id:"ST10", name:"Ramapuram", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-55609", status:"offline" },
  { id:"ST11", name:"Test Location", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-55611", status:"offline" },
  { id:"ST12", name:"Velachery", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-60010", status:"offline" },
  { id:"ST13", name:"Nelson Manickam Rd", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-98158", status:"offline" },
  { id:"ST14", name:"Gateway", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-150251", status:"offline" },
  { id:"ST15", name:"Madipakkam", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-83268", status:"offline" },
  { id:"ST16", name:"Nelson Manickam Rd", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-98160", status:"offline" },
  { id:"ST17", name:"Pammal", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-83274", status:"offline" },
  { id:"ST18", name:"Perambur", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-148164", status:"offline" },
  { id:"ST19", name:"Shriram Gateway", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-103513", status:"offline" },
  { id:"ST20", name:"Mogappair", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-162749", status:"offline" },
  { id:"ST21", name:"OMR Thoraipakkam", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-139088", status:"offline" },
  { id:"ST22", name:"Keelkattalai", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-83269", status:"offline" },
  { id:"ST23", name:"Mogappair", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-166639", status:"offline" },
  { id:"ST24", name:"Mudichur", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-83273", status:"offline" },
  { id:"ST25", name:"Mugalivakkam", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-83275", status:"offline" },
  { id:"ST26", name:"OMR Thoraipakkam", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-150253", status:"offline" },
  { id:"ST27", name:"Perambur", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-150252", status:"offline" },
  { id:"ST28", name:"Perumbakkam", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-83271", status:"offline" },
  { id:"ST29", name:"Rajakilpakkam", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-83272", status:"offline" },
  { id:"ST30", name:"Ramapuram", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-83276", status:"offline" },
  { id:"ST31", name:"T Nagar", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-166640", status:"offline" },
  { id:"ST32", name:"Velachery", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-83267", status:"offline" },
  { id:"ST33", name:"Commissary", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-84758", status:"offline" },
  { id:"ST34", name:"Nanganallur", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-83270", status:"offline" },
  { id:"ST35", name:"T Nagar", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-162750", status:"offline" },
  { id:"ST36", name:"Amazon - Global Info City", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-63367", status:"offline" },
  { id:"ST37", name:"Commissary (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-60000", status:"offline" },
  { id:"ST38", name:"ETL Phase2", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-62570", status:"offline" },
  { id:"ST39", name:"Keelakattalai (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-60001", status:"offline" },
  { id:"ST40", name:"Madipakkam (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-60002", status:"offline" },
  { id:"ST41", name:"Mudichur (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-60003", status:"offline" },
  { id:"ST42", name:"Mugalivakkam (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-60004", status:"offline" },
  { id:"ST43", name:"Nanganallur (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-60005", status:"offline" },
  { id:"ST44", name:"Pammal (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-60006", status:"offline" },
  { id:"ST45", name:"Perumbakkam (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-60007", status:"offline" },
  { id:"ST46", name:"Rajakilpakkam (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-60008", status:"offline" },
  { id:"ST47", name:"Ramapuram (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-60009", status:"offline" },
  { id:"ST48", name:"Test Location (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-55503", status:"offline" },
  { id:"ST49", name:"Velachery (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-55612", status:"offline" },
  { id:"ST50", name:"Gateway", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-98159", status:"offline" },
  { id:"ST51", name:"Amazon - Trill", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-64588", status:"offline" },
  { id:"ST52", name:"Amazon - WTC", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-66840", status:"offline" },
  { id:"ST53", name:"Ascendas", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-99796", status:"offline" },
  { id:"ST54", name:"Marina Mall", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-171277", status:"offline" },
  { id:"ST55", name:"Nelson Manickam Road", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-99167", status:"offline" },
  { id:"ST56", name:"ODC-1", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-162650", status:"offline" },
  { id:"ST57", name:"OMR Thoraipakkam (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-139085", status:"offline" },
  { id:"ST58", name:"Perambur (POS)", brand:"Ovenfresh", city:"Chennai", location_id:"STP-L-147535", status:"offline" },
];